export enum OrderStatus {
    CREATED = "CREATED",
    CHECKOUT_COMPLETED = "CHECKOUT_COMPLETED",
    PAYMENT_ACCEPTED = "PAYMENT_ACCEPTED",

    ACKNOWLEDGED = "ACKNOWLEDGED",
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    SHIPPED = "SHIPPED",
    DELIVERED = "DELIVERED",
    COMPLETED = "COMPLETED",
}
