name: Frontend Master Checks

on:
  pull_request:
    branches:
      - master
    paths:
      - 'products/**/frontend/**'
  workflow_dispatch:
    inputs:
      product:
        description: 'Product to deploy'
        required: false
        type: choice
        options:
          - all
          - customers
          - funnels
          - socials
          - websites
        default: 'all'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - id: set-matrix
      name: Detect changed products
      shell: bash
      run: |
        # If manually triggered with specific product
        if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.product }}" != "all" ]]; then
          echo "Deploying specific product: ${{ github.event.inputs.product }}"
          echo "matrix=[\"${{ github.event.inputs.product }}\"]" >> $GITHUB_OUTPUT
          exit 0
        fi

        # If manually triggered with "all", deploy all products
        if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.product }}" == "all" ]]; then
          echo "Deploying all products (manual trigger)"
          echo "matrix=[\"customers\", \"funnels\", \"socials\", \"websites\"]" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Detect file changes
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "Changed files:"
        echo "$CHANGED_FILES"

        # Check if packages directory has changes
        if echo "$CHANGED_FILES" | grep "packages/frontend"; then
          echo "Changes detected in shared packages, deploying all products"
          echo "matrix=[\"customers\", \"funnels\", \"socials\", \"websites\"]" >> $GITHUB_OUTPUT
          exit 0
        fi

        PRODUCTS=()

        # Check each product for changes without using grep -q
        if echo "$CHANGED_FILES" | grep "products/maistro-customers/frontend"; then
          echo "Changes detected in maistro-customers"
          PRODUCTS+=("customers")
        fi

        if echo "$CHANGED_FILES" | grep "products/maistro-funnels/frontend"; then
          echo "Changes detected in maistro-funnels"
          PRODUCTS+=("funnels")
        fi

        if echo "$CHANGED_FILES" | grep "products/maistro-socials/frontend"; then
          echo "Changes detected in maistro-socials"
          PRODUCTS+=("socials")
        fi

        if echo "$CHANGED_FILES" | grep "products/maistro-websites/frontend"; then
          echo "Changes detected in maistro-websites"
          PRODUCTS+=("websites")
        fi

        # Create JSON array for matrix
        if [ ${#PRODUCTS[@]} -eq 0 ]; then
          echo "No product-specific changes detected"
          echo "matrix=[]" >> $GITHUB_OUTPUT
        else
          JSON_ARRAY=$(printf '"%s",' "${PRODUCTS[@]}" | sed 's/,$//')
          echo "matrix=[${JSON_ARRAY}]" >> $GITHUB_OUTPUT
          echo "Products to deploy: [${JSON_ARRAY}]"
        fi

  build-and-deploy:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.matrix != '[]' }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        product: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
      fail-fast: false

    steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install

    - name: Lint
      run: pnpm format:${{ matrix.product }}

    - name: Lint
      run: pnpm lint:${{ matrix.product }}
    
    - name: Test
      run: pnpm test:${{ matrix.product }}
    
    - name: Build
      run: pnpm build:${{ matrix.product }}
